# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ed78580766d20f93882162154a2d599d5e334d5587136ebb19f5dccb0cca7e369863982eb4c3610c11ec21529ab420fdf3c4ccb72f85a207b0c80954bd0f361

test:
  secret_key_base: 3b5d0c2307a5a6fde2c67f690b2c659bf0e5ec14283573c54e8f9bbe72ab2852f28d70a0e3a7307cb10f7e8383753b627ea1640100b8ffadf79b1a468c64775d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
